QA code improvements to discussion.js, admin.js, lesson.js and workshop.js.
jlabusch/moodle-log-migration pull request #25
Opened 2017-05-05 08:57 UTC by carmen12

2017-05-07 22:29 UTC, jlabusch requested changes
Let's talk, maybe I'm misunderstanding something.

2017-05-07 22:29 UTC, jlabusch commented on app/lib/audit.js
> +      if (err) { return console.log(err);}
Indenting

2017-05-07 22:29 UTC, jlabusch commented on app/lib/audit.js
> +    fs.readFile('/opt/data/audit_log.sql', function (err,data) {//needed to add a ";"" at the end of the sql commands
This seems wrong... Surely we shouldn't read+write a file in passing every time we access append() or flush()?

2017-05-08 10:14 UTC, carmen12 commented
I've added the new solution that we decided on this morning. Seems to be working well now.

2017-05-08 15:34 UTC, merged