Quiz
jlabusch/moodle-log-migration pull request #3
Opened 2017-04-21 05:54 UTC by botond-hegedus-dev

quiz.js

2017-04-22 00:41 UTC, jlabusch requested changes
functions for sql_old_2pass and sql_match have similar errors throughout the file, possibly caused by copy-paste.

2017-04-22 00:41 UTC, jlabusch commented on lib/quiz.js
> +            }
This looks unfinished; what's the query you want to execute if id does exist?

2017-04-22 00:41 UTC, jlabusch commented on lib/quiz.js
> +                :
See comment from other PR - the ternary operator isn't being used correctly here.

2017-04-22 00:41 UTC, jlabusch commented on lib/quiz.js
> +                console.log('No course module ID from DB ' + JSON.stringify(row));
This is redundant; just return null and the caller will print the row for you with an error message.

2017-04-24 08:08 UTC, botond-hegedus-dev commented on lib/quiz.js
> +                :
Fixed

2017-04-24 08:09 UTC, botond-hegedus-dev commented
I made some changes, ready to test

2017-04-24 10:56 UTC, jlabusch approved these changes

2017-04-24 10:56 UTC, merged