Assign
jlabusch/moodle-log-migration pull request #6
Opened 2017-04-21 11:04 UTC by botond-hegedus-dev

app_1           | SELECT cm.id AS cm_id FROM mdl_course_modules cm  LEFT JOIN mdl_course c ON c.id = cm.course  JOIN mdl_assign a ON a.id = cm.instance  JOIN mdl_modules m ON m.id = cm.module  JOIN mdl_user u ON (u.email = 'laura.aparisi@barcelona.msf.org' OR u.username = 'laparisi')  WHERE m.name = 'assign' AND c.shortname = 'PPD_FirstQuarter2015' AND a.name = 'What is MSF for you?'  

This provides 2 results in my LOCAL NEW DB from 2017-04-01

But by running the script I get this instead:

app_1           |   No course module ID from DB {"id":1976864,"time":1424085174,"userid":185,"ip":"10.111.112.125","course":274,"module":"assign","cmid":24348,"action":"add","url":"view.php?id=24348","info":"3937","u_username":"laparisi","u_email":"laura.aparisi@barcelona.msf.org","course_shortname":"PPD_FirstQuarter2015","assign_name":"What is MSF for you?"}
app_1           | ERROR for mdl_log.assign.add: insufficient data for query - {"id":1976864,"time":1424085174,"userid":185,"ip":"10.111.112.125","course":274,"module":"assign","cmid":24348,"action":"add","url":"view.php?id=24348","info":"3937","u_username":"laparisi","u_email":"laura.aparisi@barcelona.msf.org","course_shortname":"PPD_FirstQuarter2015","assign_name":"What is MSF for you?"}

app_1           | completed mdl_log.assign
app_1           | 	mdl_log.assign.add.count: 314
app_1           | 	mdl_log.assign.add.time: 136ms

2017-04-22 00:34 UTC, jlabusch requested changes

2017-04-22 00:34 UTC, jlabusch commented on lib/assign.js
> +            }
This looks unfinished... What should it return in the success case?

2017-04-22 00:34 UTC, jlabusch commented on lib/assign.js
> +                return null;
The "return null" statement here is dead code... Did you mean to have console.log()'s return value be the result of sql_match()?

Also, you'll already get the content of row[] printed out by the caller if you return null here, so you might not need console.log() at all.

2017-04-22 00:34 UTC, jlabusch commented on lib/assign.js
> +            return row.cm_id ?
There's no such field in the result of your sql_old query. Do you mean row.cmid?

2017-04-24 08:11 UTC, botond-hegedus-dev commented on lib/assign.js
> +            }
Fixed

2017-04-24 08:15 UTC, botond-hegedus-dev commented on lib/assign.js
> +                return null;
Fixed

2017-04-24 08:17 UTC, botond-hegedus-dev commented on lib/assign.js
> +            return row.cm_id ?
Fixed

2017-04-24 11:03 UTC, jlabusch approved these changes

2017-04-24 11:03 UTC, merged